server:
  port: 9527
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由功能，使用微服务的名称进行路由
      routes:
        - id: user_route      # 路由的id，没有固定规则但要求唯一，建议配置服务名称
          # uri: http://localhost:8001  # 匹配后提供的服务地址 （使用固定地址）
          uri: lb://user-provider  # 匹配后提供的服务地址 （使用服务名称，须增加 discovery.locator.enabled=true 配置）
          predicates:
            - Path=/user/** # 断言，根据此路径进行匹配

        - id: baidu_route
          uri: https://www.baidu.com
          predicates:
            - Path=/baidu/**
eureka:
  instance:
    hostname: gateway-service
  client:
    service-url:
      register-with-eureka: true
      fatch-registry: true
      defaultZone: http://localhost:7001/eureka/
