server:
  port: 9527
spring:
  application:
    name: spring-cloud-zuul

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka （单机）
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/ #（集群）
  instance:
    instance-id: spring-cloud-config-zuul9527 # 自定义服务名称信息
    prefer-ip-address: true # 访问路径可以现实IP

#配置路由规则：这里的配置表示，访问/baidu/** 直接重定向到http://www.baidu.com/**
zuul:
  routes:
    baidu.path: /baidu/**
    baidu.url: http://www.baidu.com/

    myUser.serviceId: user-provider
    myUser.path: /myUser/**