server:
  port: 8081

eureka:
  client: #客户端注册进eureka服务列表内
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/ #（集群）

#ribbon:
#    # 指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
#    ReadTimeout: 10000
#    # 指的是建立连接后从服务器读取到可用资源所用的时间
#    ConnectTimeout: 10000

#feign:
#  client:
#    config:
#      default:
#        # 指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
#        ReadTimeout: 10000
#        # 指的是建立连接后从服务器读取到可用资源所用的时间
#        ConnectTimeout: 10000

logging:
  level:
    # feign 日志以什么级别监控哪个接口
    com.chaytech.api.user.UserApi: debug
