server:
  port: 9002
spring:
  application:
    name: spring-cloud-config-client-9002
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: '*'